name: Task 3 - SBOM with Syft

on:
  push:
    branches: ["master"]

jobs:
  sbom:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Verify Syft installation
        run: syft version

      - name: Generate SBOM for DVJA
        run: |
          syft dir:. -o cyclonedx-json > dvja-sbom.json

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: dvja-sbom
          path: dvja-sbom.json
