name: Task 5 - SBOM + Grype Scan

on:
  push:
    branches: ["master"]

jobs:
  sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate SBOM using Syft Action
        uses: anchore/sbom-action@v0
        with:
          path: .
          format: cyclonedx-json
          output-file: dvja-sbom.json

      - name: Install Grype
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b .

      - name: Scan SBOM with Grype and save report
        run: |
          ./grype sbom:dvja-sbom.json -o table > grype-report.txt || true

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: dvja-sbom
          path: dvja-sbom.json

      - name: Upload Grype report
        uses: actions/upload-artifact@v4
        with:
          name: grype-report
          path: grype-report.txt
