name: Task 4 - SBOM with Syft Action

on:
  push:
    branches: ["master"]

jobs:
  sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate SBOM using Syft Action
        uses: anchore/sbom-action@v0
        with:
          path: .
          format: cyclonedx-json
          output-file: dvja-sbom.json

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: dvja-sbom-task4
          path: dvja-sbom.json
